style: [CAMPUSIL-402] Add new design for login, register, password ...
edx-olive/themes-old pull request #151
Opened 2023-02-19 14:55 UTC by bahalula

https://campusil.atlassian.net/browse/CAMPUSIL-402

2023-02-20 12:15 UTC, vladimirCampusGovIl requested changes

2023-02-20 12:15 UTC, vladimirCampusGovIl commented on lms/templates/student_account/login.underscore
> +            console.log(provider);
@bahalula, Need to remove this line from the code.

2023-02-21 08:53 UTC, bahalula commented on lms/templates/student_account/login.underscore
> +            console.log(provider);
I removed it.

2023-02-28 09:15 UTC, vladimirCampusGovIl approved these changes

2023-03-06 07:32 UTC, merged